config/routes.rb
Rails.application.routes.draw do
  root to: 'artists#index'

  resources :artists do
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:show, :edit]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:destroy, :edit, :update]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def edit
  end


  def show
    @artist = Artist.find(params[:id])
  end

  def destroy
    @artist.destroy

    redirect_to artists_path
  end

  def update
    @artist.update(artist_params)

    redirect_to artist_path(@artist)
  end

  private

    def artist_params
      params.require(:artist).permit(:name, :image_path)
    end

    def set_artist
      @artist = Artist.find(params[:id])
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :set_artist, only: [:new, :create, :index]

  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.create(song_params)

    redirect_to song_path(@song)
  end

  def show
  end

  def update
    @song.update(song_params)

    redirect_to song_path(@song)
  end

  def index
    @songs = Song.all
  end

  def destroy
    @song.destroy

    redirect_to songs_path
  end

  def edit
  end

  private

    def song_params
      params.require(:song).permit(:title)
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<h1>Artist Index</h1>

<% @artists.each do |artist| %>
<div class="row">
  <div class="col s12 l3">
    <div class="card">
      <div class="card-image">
        <img src="<%=artist.image_path%>">
      </div>
      <div class="card-action">
        <a <%= link_to artist.name, artist_path(artist) %></a>
      </div>
    </div>
  </div>
  <% end %>
</div>
<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_path %>
<br>
<a class="waves-effect waves-light btn" <%= link_to "Edit", edit_artist_path(@artist) %></a>
<br>
<a class="waves-effect waves-light btn" <%= link_to "Delete", artist_path(@artist), method: :delete, data: {confirm: "Really delete the artist?"} %></a>
<br>
<a class="waves-effect waves-light btn" <%= link_to "New song", new_artist_song_path(@artist) %></a>
<br>
<%= link_to "<< Back to Artists Index", artists_path %>



<div class="fixed-action-btn">
    <a class="btn-floating btn-large red">
      <i class="large material-icons">mode_edit</i>
    </a>
    <ul>
      <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
      <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
      <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
      <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
    </ul>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.css">
    <title>MixMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.js"></script>
  </body>
</html>

app/views/songs/new.html.erb
<h1>New Song</h1>
<p>Add a new song for <%= @artist.name %></p>
<%= form_for([@artist, @song]) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<p><%= link_to @song.artist.name, artist_path(@song.artist) %></p>
<p><%= link_to "Edit",  edit_song_path(@song)%></p>